name: R-CMD-check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libhdf5-dev

      - name: Install BiocManager and dependencies
        shell: Rscript {0}
        run: |
          install.packages("BiocManager")
          BiocManager::install()
          BiocManager::install(c("SingleCellExperiment", "SummarizedExperiment", "S4Vectors"))

      - name: Install R package dependencies
        shell: Rscript {0}
        run: |
          install.packages(c("remotes", "testthat", "covr"))

      - name: Install package
        shell: Rscript {0}
        run: |
          remotes::install_local(dependencies = TRUE)

      - name: Check package
        run: |
          R CMD check --no-manual --as-cran .
        env:
          _R_CHECK_FORCE_SUGGESTS_: false

      - name: Test coverage
        shell: Rscript {0}
        run: |
          covr::codecov()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
