name: R-CMD-check

on:
  push:
  pull_request:

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: /home/runner/work/_temp/Library
      TZ: UTC
      _R_CHECK_SYSTEM_CLOCK_: FALSE
      NOT_CRAN: true
      _R_CHECK_FORCE_SUGGESTS_: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anndata

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev
          
      - name: Install Bioconductor packages
        run: |
          if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
          BiocManager::install(c("SingleCellExperiment", "SummarizedExperiment", "S4Vectors"))
        shell: Rscript {0}

      - name: Install R package dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install package
        run: |
          remotes::install_local()
        shell: Rscript {0}

      - name: Check package
        run: |
          R CMD check --no-manual --as-cran .

      - name: Test coverage
        run: |
          covr::codecov()
        shell: Rscript {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
