name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages('BiocManager')
          BiocManager::install(c('SingleCellExperiment', 'SummarizedExperiment', 'S4Vectors', 'Matrix'))
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install package
        run: |
          remotes::install_local()
        shell: Rscript {0}

      - name: Check package
        run: |
          R CMD check --no-manual --as-cran .
        shell: bash

      - name: Test coverage
        run: |
          install.packages('covr')
          Rscript -e 'covr::codecov()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
